<?php

define(ADMIN_ACCESS_PAGE, 0);
define(ADMIN_ACCESS_ITEM, 1);
define(ADMIN_ACCESS_MISC, 2);

/**
 * 注意！
 * 这个数组的各项的index，有非常严格的规定，不清楚的人，绝对不允许修改这个数组$ADMIN_PAGE_CONFIG
 *
 * 注意！！！ 新加的功能菜单项 必须配置一个大于当前所有索引值的索引，位置可以任意了。
 */

global $ADMIN_PAGE_CONFIG;
$ADMIN_PAGE_CONFIG = array(
	0   => array('name'=>'服务端信息',         'class'=>'服务器信息',             'url'=>'statistics/server_info.php'),
	9   => array('name'=>'单服概况说明',       'class'=>'服务器信息',             'url'=>'world/game_survey.php'),
	21  => array('name'=>'封禁帐号',           'class'=>'玩家信息管理和查询',     'url'=>'online/ban_account.php'),
	60  => array('name'=>'封禁IP',             'class'=>'玩家信息管理和查询',     'url'=>'online/ban_ip.php'),
	22  => array('name'=>'直接登录玩家帐号',   'class'=>'玩家信息管理和查询',     'url'=>'system/direct_login_user_account.php'),
	23  => array('name'=>'直接创建GM角色',     'class'=>'玩家信息管理和查询',     'url'=>'system/create_gm_role.php'),
	63  => array('name'=>'称号管理',           'class'=>'玩家信息管理和查询',     'url'=>'gamer/gamer_title.php'),
	20  => array('name'=>'玩家状态查询',       'class'=>'玩家信息管理和查询',     'url'=>'gamer/gamer_status_view.php'),
	24  => array('name'=>'玩家交易查询',       'class'=>'玩家信息管理和查询',     'url'=>'gamer/exchange_manage.php'),
	25  => array('name'=>'信件交易查询',       'class'=>'玩家信息管理和查询',     'url'=>'gamer/letter_exchange_manage.php'),
	61  => array('name'=>'玩家任务状态查询',   'class'=>'玩家信息管理和查询',     'url'=>'gamer/gamer_task_status.php'),
	62  => array('name'=>'boss状态查询',       'class'=>'玩家信息管理和查询',     'url'=>'gamer/boss_state_view.php'),
	66  => array('name'=>'个人拉镖查询',       'class'=>'玩家信息管理和查询',     'url'=>'gamer/personal_ybc_log.php'),
	94  => array('name'=>'清理拉镖状态',       'class'=>'玩家信息管理和查询',     'url'=>'gamer/clear_ybc_state.php'),
	71  => array('name'=>'讨伐敌营查询',       'class'=>'玩家信息管理和查询',     'url'=>'gamer/role_map_copy_view.php'),
	87  => array('name'=>'登录历史查询',       'class'=>'玩家信息管理和查询',     'url'=>'gamer/gamer_login_check.php'),
	91  => array('name'=>'个人商贸查询',       'class'=>'玩家信息管理和查询',     'url'=>'stat/trading_log_view.php'),
	93  => array('name'=>'玩家下线查询',       'class'=>'玩家信息管理和查询',     'url'=>'gamer/user_offline.php'),
	105 => array('name'=>'师徒副本查询',       'class'=>'玩家信息管理和查询',     'url'=>'analysis/educate.php'),
	108 => array('name'=>'玩家宠物查询',       'class'=>'玩家信息管理和查询',     'url'=>'gamer/gamer_pet_info.php'),
	109 => array('name'=>'宠物状态明细',       'class'=>'玩家信息管理和查询',     'url'=>'gamer/pet_info_view.php'),
	111 => array('name'=>'宠物信息统计',       'class'=>'玩家信息管理和查询',     'url'=>'pet/pet_sum.php'),
    120 => array('name'=>'宠物训练统计',        'class'=>'玩家信息管理和查询',     'url'=>'pet/pet_training.php'),
	115 => array('name'=>'玩家刺探任务查询',   'class'=>'玩家信息管理和查询',     'url'=>'gamer/citan_guotan_view.php'),
	116 => array('name'=>'玩家守边任务查询',   'class'=>'玩家信息管理和查询',     'url'=>'gamer/shoubian_view.php'),
	122 => array('name'=>'VIP信息查询',   'class'=>'玩家信息管理和查询',     'url'=>'gamer/gamer_vip.php'),
	26  => array('name'=>'查看聊天日志',       'class'=>'消息管理',               'url'=>'chat/chat_log.php'),
	129 => array('name'=>'查看群组聊天记录',   'class'=>'消息管理',               'url'=>'chat/level_chat_log.php'),
	27  => array('name'=>'设置玩家禁言',       'class'=>'消息管理',               'url'=>'chat/chat_ban_user.php'),
	28  => array('name'=>'给玩家发信',         'class'=>'消息管理',               'url'=>'chat/send_email.php'),
	29  => array('name'=>'消息广播列表',       'class'=>'消息管理',               'url'=>'chat/broadcast_message_list.php'),
	68  => array('name'=>'批量发信',           'class'=>'消息管理',               'url'=>'chat/send_email_batch.php'),
	1   => array('name'=>'当前在线用户',       'class'=>'在线与注册',             'url'=>'online/cur_online_user.php'),
	2   => array('name'=>'历史在线数据',       'class'=>'在线与注册',             'url'=>'online/online_view.php'),
	3   => array('name'=>'当前注册信息统计',   'class'=>'在线与注册',             'url'=>'register/today.php'),
	4   => array('name'=>'在线柱状图',         'class'=>'在线与注册',             'url'=>'online/online_stat.php'),
	5   => array('name'=>'所有注册用户',       'class'=>'在线与注册',             'url'=>'gamer/all_gamer_view.php'),
	6   => array('name'=>'注册数据统计',       'class'=>'在线与注册',             'url'=>'gamer/gamer_reg_stat.php'),
	7   => array('name'=>'分时注册统计',      'class'=>'在线与注册',             'url'=>'gamer/reg_stat_by_hour.php'),
	10  => array('name'=>'玩家充值记录',       'class'=>'充值与消费',             'url'=>'pay/pay_view.php'),
	11  => array('name'=>'充值日志/补单',      'class'=>'充值与消费',             'url'=>'pay/pay_status_history.php'),
	15  => array('name'=>'玩家充值排行',       'class'=>'充值与消费',             'url'=>'pay/pay_rank.php'),
	19  => array('name'=>'首次充值统计',       'class'=>'充值与消费',             'url'=>'pay/first_pay.php'),
	12  => array('name'=>'分时充值统计',       'class'=>'充值与消费',             'url'=>'pay/pay_hour.php'),
	13  => array('name'=>'按天充值统计',       'class'=>'充值与消费',             'url'=>'pay/pay_day.php'),
	14  => array('name'=>'按月充值统计',       'class'=>'充值与消费',             'url'=>'pay/pay_month.php'),
	16  => array('name'=>'银子使用记录',       'class'=>'充值与消费',             'url'=>'pay/silver_use_log_view.php'),
	17  => array('name'=>'元宝使用记录',       'class'=>'充值与消费',             'url'=>'pay/gold_use_log_view.php'),
	114 => array('name'=>'元宝赠送记录',       'class'=>'充值与消费',             'url'=>'pay/log_send_gold.php'),
	18  => array('name'=>'赠送元宝银子',       'class'=>'充值与消费',             'url'=>'pay/send_gold.php'),
	35  => array('name'=>'所有道具列表',       'class'=>'道具管理和统计',         'url'=>'gamer/gamer_item_list.php'),
	34  => array('name'=>'赠送普通道具',       'class'=>'道具管理和统计',         'url'=>'gamer/send_goods.php'),
	40  => array('name'=>'赠送货币道具',       'class'=>'道具管理和统计',         'url'=>'gamer/send_money_goods.php'),
	41  => array('name'=>'赠送超级道具',       'class'=>'道具管理和统计',         'url'=>'gamer/send_super_goods.php'),
	69  => array('name'=>'批量送道具',         'class'=>'道具管理和统计',         'url'=>'gamer/send_goods_batch.php'),
	36  => array('name'=>'玩家道具使用记录',   'class'=>'道具管理和统计',         'url'=>'gamer/gamer_item_use_view.php'),
	37  => array('name'=>'道具跟踪查询',       'class'=>'道具管理和统计',         'url'=>'gamer/item_log_manage.php'),
	38  => array('name'=>'道具消耗排行',       'class'=>'道具管理和统计',         'url'=>'analysis/item_consume_order.php'),
	39  => array('name'=>'商店购买道具排行',   'class'=>'道具管理和统计',         'url'=>'analysis/item_buy_order.php'),
	54  => array('name'=>'登录公告设置',       'class'=>'游戏系统设置',           'url'=>'setting/system_notice.php'),
	104 => array('name'=>'连续登录奖励设置',   'class'=>'游戏系统设置',           'url'=>'setting/conlogin_reward.php'),
	8   => array('name'=>'登录数据统计分析',   'class'=>'游戏基础数据统计',       'url'=>'online/login_data_stat.php'),
	47  => array('name'=>'创建角色页流失率',   'class'=>'游戏基础数据统计',       'url'=>'stat/create_user_stat.php'),
	48  => array('name'=>'日/周用户登录量统计','class'=>'游戏基础数据统计',       'url'=>'stat/user_leave_count.php'),
	49  => array('name'=>'等级流失率',         'class'=>'游戏基础数据统计',       'url'=>'analysis/login_event_rate.php'),
	50  => array('name'=>'时间流失率',         'class'=>'游戏基础数据统计',       'url'=>'gamer/lost_user_event.php'),
	51  => array('name'=>'任务统计',           'class'=>'游戏基础数据统计',       'url'=>'gamer/task_count_rate.php'),
	52  => array('name'=>'势力统计',           'class'=>'游戏基础数据统计',       'url'=>'stat/faction_stat.php'),
	53  => array('name'=>'激活码统计',         'class'=>'游戏基础数据统计',       'url'=>'stat/activate_code_stat.php'),
	65  => array('name'=>'商贸日志',           'class'=>'游戏基础数据统计',       'url'=>'stat/trading_log.php'),
	73  => array('name'=>'财富统计',           'class'=>'游戏基础数据统计',       'url'=>'analysis/money_stat.php'),
	76  => array('name'=>'每日登录统计',       'class'=>'游戏基础数据统计',       'url'=>'stat/everyday_online_stat.php'),
	78  => array('name'=>'活跃与忠诚用户统计', 'class'=>'游戏基础数据统计',       'url'=>'gamer/user_count.php'),
	79  => array('name'=>'活跃与忠诚用户图',   'class'=>'游戏基础数据统计',       'url'=>'gamer/user_count_graph.php'),
	82  => array('name'=>'门派&充值数据统计',  'class'=>'游戏基础数据统计',       'url'=>'stat/family_stat.php'),
	88  => array('name'=>'师徒数据统计',       'class'=>'游戏基础数据统计',       'url'=>'stat/master_stat.php'),
	92  => array('name'=>'3级玩家行为统计',    'class'=>'游戏基础数据统计',       'url'=>'analysis/game_loading.php'),
	96  => array('name'=>'钱庄挂单记录',       'class'=>'游戏基础数据统计',       'url'=>'analysis/bank_sheet_view.php'),
	97  => array('name'=>'钱庄挂单统计',       'class'=>'游戏基础数据统计',       'url'=>'analysis/bank_sheet_stat.php'),
	98  => array('name'=>'活跃用户等级分布',   'class'=>'游戏基础数据统计',       'url'=>'gamer/active_user_level_distribution.php'),
	99  => array('name'=>'用户登录等级分布',   'class'=>'游戏基础数据统计',       'url'=>'gamer/login_level_distribution.php'),
	100 => array('name'=>'道具消耗统计',       'class'=>'游戏基础数据统计',       'url'=>'analysis/item_consum_sum.php'),
	103 => array('name'=>'国运统计',           'class'=>'游戏基础数据统计',       'url'=>'stat/faction_trans.php'),
	102 => array('name'=>'大明宝藏统计',       'class'=>'游戏基础数据统计',       'url'=>'analysis/country_treasure_sum.php'),
	64  => array('name'=>'讨伐敌营统计',       'class'=>'游戏基础数据统计',       'url'=>'gamer/map_copy_stat.php'),
	106 => array('name'=>'师徒副本统计',       'class'=>'游戏基础数据统计',       'url'=>'analysis/educate_sum.php'),
	110 => array('name'=>'宠物拥有度统计',     'class'=>'游戏基础数据统计',       'url'=>'pet/pet_keep_sum.php'),
	112 => array('name'=>'宠物相关操作统计',   'class'=>'游戏基础数据统计',       'url'=>'pet/pet_action_sum.php'),
	117 => array('name'=>'国探任务统计',       'class'=>'游戏基础数据统计',       'url'=>'stat/guotan_stat.php'),
	118 => array('name'=>'守边任务统计',       'class'=>'游戏基础数据统计',       'url'=>'stat/shoubian_stat.php'),
	123 => array('name'=>'VIP信息统计',        'class'=>'游戏基础数据统计',       'url'=>'stat/vip_info_stat.php'),
	139 => array('name'=>'48小时流失统计',     'class'=>'游戏基础数据统计',       'url'=>'stat/level_1_2_liushi.php'),
	132 => array('name'=>'玩家断线原因统计',     'class'=>'游戏基础数据统计',       'url'=>'stat/user_offline_stat.php'),
	30  => array('name'=>'王座争霸战',         'class'=>'活动管理',               'url'=>'event/warofking.php'),
	31  => array('name'=>'国王和国库银两设置', 'class'=>'活动管理',               'url'=>'event/office.php'),
	32  => array('name'=>'讨伐敌营副本',       'class'=>'活动管理',               'url'=>'event/vwf.php'),
	33  => array('name'=>'大明宝藏副本',       'class'=>'活动管理',               'url'=>'event/country_treasure.php'),
	132 => array('name'=>'天工开物',           'class'=>'活动管理',               'url'=>'event/refining_box.php'),
	121 => array('name'=>'师徒副本',           'class'=>'活动管理',               'url'=>'event/educate_fb.php'),
	75  => array('name'=>'开启国运',           'class'=>'活动管理',               'url'=>'event/faction_ybc.php'),
	77  => array('name'=>'国战管理',           'class'=>'活动管理',               'url'=>'event/waroffaction.php'),
	89  => array('name'=>'查看活动配置',       'class'=>'活动管理',               'url'=>'event/activity_config.php'),
	90  => array('name'=>'首充开关管理',       'class'=>'活动管理',               'url'=>'event/pay_first.php'),
	119 => array('name'=>'开启国探',           'class'=>'活动管理',               'url'=>'event/guotan.php'),
	70  => array('name'=>'门派信息',           'class'=>'综合查询',               'url'=>'gamer/admin_family_manage.php'),
	67  => array('name'=>'门派拉镖查询',       'class'=>'综合查询',               'url'=>'gamer/family_ybc_log.php'),
	42  => array('name'=>'元宝使用统计',       'class'=>'消费数据统计',           'url'=>'analysis/gold_use_stat.php'),
	74  => array('name'=>'首次元宝消费统计',   'class'=>'消费数据统计',           'url'=>'analysis/gold_first_use_stat.php'),
	95  => array('name'=>'元宝日消耗统计',     'class'=>'消费数据统计',           'url'=>'analysis/gold_consum_role_count.php'),
	84  => array('name'=>'不同付费区间元宝消耗','class'=>'消费数据统计',          'url'=>'analysis/gold_consum_by_pay_level.php'),
	45  => array('name'=>'元宝存量与消耗',     'class'=>'消费数据统计',           'url'=>'analysis/gold_save_and_consume.php'),
	80  => array('name'=>'元宝分时消耗图',     'class'=>'消费数据统计',           'url'=>'analysis/gold_consum_hour.php'),
	81  => array('name'=>'元宝分类消耗图',     'class'=>'消费数据统计',           'url'=>'analysis/gold_consum_by_type.php'),
	83  => array('name'=>'元宝分等级消耗图',   'class'=>'消费数据统计',           'url'=>'analysis/gold_consum_by_level.php'),
	43  => array('name'=>'玩家元宝消费排行',   'class'=>'消费数据统计',           'url'=>'pay/gold_use_list.php'),
	46  => array('name'=>'玩家元宝余额排行',   'class'=>'消费数据统计',           'url'=>'pay/gold_remain_list.php'),
	44  => array('name'=>'银子使用统计',       'class'=>'消费数据统计',           'url'=>'analysis/silver_use_stat.php'),
	72  => array('name'=>'银子存量与消耗',     'class'=>'消费数据统计',           'url'=>'analysis/silver_save_and_consume.php'),
	85  => array('name'=>'银子分时消耗图',     'class'=>'消费数据统计',           'url'=>'analysis/silver_consum_hour.php'),
	86  => array('name'=>'银子分类消耗图',     'class'=>'消费数据统计',           'url'=>'analysis/silver_consum_by_type.php'),
	55  => array('name'=>'后台管理记录',       'class'=>'后台管理',               'url'=>'system/admin_log_view.php'),
	56  => array('name'=>'用户管理',           'class'=>'后台管理',               'url'=>'system/admin_user_management.php'),
	57  => array('name'=>'组管理',             'class'=>'后台管理',               'url'=>'system/admin_group_management.php'),
	58  => array('name'=>'系统全局变量',       'class'=>'系统管理',               'url'=>'setting/config_setting.php'),
	59  => array('name'=>'修改登录密码',       'class'=>'系统管理',               'url'=>'setting/password.php','desc'=>'可对外'),
	107 => array('name'=>'开关控制',           'class'=>'系统管理',               'url'=>'setting/switch_manager.php'),
	101 => array('name'=>'查看错误日志',       'class'=>'运维管理',               'url'=>'system/admin_error_log_view.php'),
	113 => array('v' => 'debug', 'name'=>'累积经验',           'class'=>'测试辅助',               'url'=>'test/test_accumulate_exp.php'),
	124  => array('name'=>'同步玩家镖车位置',  'class'=>'玩家信息管理和查询',     'url'=>'gamer/syn_ybc_pos.php'),
	125 => array('name'=>'个人副本查询',       'class'=>'玩家信息管理和查询',     'url'=>'analysis/personal_fb.php'),
	126 => array('name'=>'日常福利统计',       'class'=>'游戏基础数据统计',     'url'=>'analysis/activity_benefit_stat.php'),
	127  => array('name'=>'门派采集活动控制',   'class'=>'活动管理',               'url'=>'event/family_collect.php'),
	128 => array('name'=>'场景副本统计',     'class'=>'游戏基础数据统计',       'url'=>'stat/scene_war_stat.php'),
	130  => array('name'=>'导出地图流失率数据',   'class'=>'游戏基础数据统计',               'url'=>'system/gen_map_liushi.php'),
	131  => array('name'=>'玩家升级日志查询',   'class'=>'玩家信息管理和查询',               'url'=>'gamer/gamer_level_log.php'),
	133  => array('name'=>'副本掉落道具统计',   'class'=>'游戏基础数据统计',      'url'=>'stat/fb_drop_thing_stat.php'),
	134  => array('name'=>'修改玩家数据',       'class'=>'玩家信息管理和查询',     'url'=>'gamer/gamer_status_modify.php'),
	135  => array('name'=>'副本数据统计',   'class'=>'游戏基础数据统计',      'url'=>'stat/fb_data_stat.php'),
	136  => array('name'=>'玩家升级时间统计',   'class'=>'游戏基础数据统计',      'url'=>'stat/role_level_stat.php'),
	137  => array('name'=>'升级玩家统计',  'class'=>'游戏基础数据统计',     'url'=>'gamer/new_level_count.php'),
	138 => array('name'=>'宠物信息查询',       'class'=>'玩家信息管理和查询',     'url'=>'pet/pet_info.php'),
	140  => array('name'=>'发送批量信件/道具结果',           'class'=>'消息管理',               'url'=>'chat/send_batch_result.php'),
	141  => array('name'=>'查看更新版本记录',           'class'=>'运维管理',               'url'=>'system/version_log.php'),
	142 => array('v' => 'debug', 'name'=>'传奇目标',           'class'=>'测试辅助',               'url'=>'test/test_goal.php'),
	143 => array('name'=>'道具分类查询',       'class'=>'道具管理和统计',     'url'=>'analysis/gold_cost_list.php'),
	145 => array('name'=>'商店促销设置',   'class'=>'游戏系统设置',           'url'=>'setting/shop_cuxiao.php'),
	146 => array('v' => 'debug', 'name'=>'模拟战斗结果',   'class'=>'测试辅助',           'url'=>'test/test_fight.php'),
);
