%% Generated by the protocol buffer compiler.  DO NOT EDIT!

-record(b_server_auth_tos, {agent_name, game_id, ticket}).
-record(b_server_auth_toc, {succ=true, reason, ip, port}).
-record(b_server_msg_toc, {msg}).
-record(b_server_unique_toc, {unique}).
-record(b_consume_gold_tos, {role_id, role_name, account_name, level, gold_bind, gold_unbind, mtime, mtype, mdetail, itemid, amount}).
-record(b_pay_log_tos, {account_name, role_name, role_id, order_id, pay_money, pay_gold, give_gold, role_level, pay_time, pay_date_time, year, month, day, hour, online_day}).
-record(adm_gm_complaint, {account_name, role_id, role_name, pay_amount, level, mtime, mtype, mtitle, content}).
-record(adm_gm_evaluate, {reply_id, role_id, mark}).
-record(adm_gm_notify_reply, {reply_id, succ, reason}).
