package modules {
	import com.components.MessageIconManager;
	
	import modules.Activity.ActivityModule;
	import modules.achievement.AchievementModule;
	import modules.bank.BankModule;
	import modules.bigExpresion.BigExpresionModule;
	import modules.broadcast.BroadcastModule;
	import modules.chat.ChatModule;
	import modules.collect.CollectModule;
	import modules.conlogin.ConloginModule;
	import modules.countrytreasure.CountryTreasureModule;
	import modules.deal.DealModule;
	import modules.deal.NpcDealModule;
	import modules.driver.DriverModule;
	import modules.duplicate.DuplicateModule;
	import modules.educate.EducateModule;
	import modules.equiponekey.EquipOneKeyModule;
	import modules.factionsWar.FactionWarModule;
	import modules.family.FamilyDepotModule;
	import modules.family.FamilyModule;
	import modules.family.FamilySkillModule;
	import modules.family.FamilyYBCModule;
	import modules.familyCollect.FamilyCollectModule;
	import modules.finery.FineryModule;
	import modules.flowers.FlowerModule;
	import modules.forgeshop.ForgeshopModule;
	import modules.friend.FriendsModule;
	import modules.gift.GiftModule;
	import modules.gm.GMModule;
	import modules.goal.GoalModule;
	import modules.greenHand.GreenHandModule;
	import modules.help.HelpManager;
	import modules.heroFB.HeroFBModule;
	import modules.jail.JailModule;
	import modules.letter.LetterModule;
	import modules.login.LoginModule;
	import modules.market.MarketModule;
	import modules.mission.MissionFBModule;
	import modules.mission.MissionModule;
	import modules.mount.mountModule;
	import modules.mypackage.PackageModule;
	import modules.navigation.NavigationModule;
	import modules.nearPlayer.NearPlayerModule;
	import modules.needfire.NeedfieModule;
	import modules.npc.NPCModule;
	import modules.official.OfficialModule;
	import modules.personalybc.PersonalYbcModule;
	import modules.pet.PetModule;
	import modules.playerGuide.PlayerGuideModule;
	import modules.present.PresentModule;
	import modules.prestige.PrestigeModule;
	import modules.rank.RankModule;
	import modules.reward.RewardModule;
	import modules.rider.RiderModule;
	import modules.robKingWar.RobKingWarModule;
	import modules.roleStateG.RoleStateModule;
	import modules.scene.SceneModule;
	import modules.scene.cases.ChatCase;
	import modules.scene.cases.CollectCase;
	import modules.scene.cases.DealCase;
	import modules.scene.cases.FightCase;
	import modules.scene.cases.MapCase;
	import modules.scene.cases.MonsterCase;
	import modules.scene.cases.MoveCase;
	import modules.scene.cases.PetCase;
	import modules.scene.cases.RobKingSceneCase;
	import modules.scene.cases.Role2Case;
	import modules.scene.cases.ServerNPCCase;
	import modules.scene.cases.SettingCase;
	import modules.scene.cases.YBCCase;
	import modules.sceneWarFb.SceneWarFbModule;
	import modules.shop.ShopModule;
	import modules.skill.SkillModule;
	import modules.skillTree.SkillTreeModule;
	import modules.smallMap.SmallMapModule;
	import modules.spy.SpyModule;
	import modules.stat.StatModule;
	import modules.system.SystemModule;
	import modules.team.TeamModule;
	import modules.tourist.TouristModule;
	import modules.trading.TradingModule;
	import modules.training.TrainModule;
	import modules.trap.TrapModule;
	import modules.vip.VipModule;
	import modules.warehouse.WarehouseModule;

	public class ModuleFactory {
		public function ModuleFactory() {
		}

		public static function createLoginModule():void {
			LoginModule.getInstance();
		}

		public static function createModules():void {
			SceneModule.getInstance();
			MapCase.getInstance();
			MoveCase.getInstance();
			ChatCase.getInstance();
			FightCase.getInstance();
			MonsterCase.getInstance();
			CollectCase.getInstance();
			PetCase.getInstance();
			Role2Case.getInstance();
			ServerNPCCase.getInstance();
			SettingCase.getInstance();
			DealCase.getInstance();
			YBCCase.getInstance();
			//AccumulateExpModule.getInstace();
			AchievementModule.getInstance();
			ActivityModule.getInstance();
			BankModule.getInstance();
			BigExpresionModule.getInstance();
			ChatModule.getInstance();
			BroadcastModule.getInstance(); //此实例必须在 ChatModel之后初始化
			CollectModule.getInstance();
			ConloginModule.getInstance();
			CountryTreasureModule.getInstance();
			DealModule.getInstance();
			DuplicateModule.getInstance();
			EducateModule.getInstance();
			EquipOneKeyModule.getInstance();
			FactionWarModule.getInstance();
			FamilyDepotModule.getInstance();
			FamilyModule.getInstance();
			FamilyYBCModule.getInstance();
			FamilySkillModule.getInstance();
			FlowerModule.getInstance();
			ForgeshopModule.getInstance();
			FriendsModule.getInstance();
			GMModule.getInstance();
			GreenHandModule.getInstance();
			JailModule.getInstance();
			LetterModule.getInstance();
			PackageModule.getInstance();
			NavigationModule.getInstance();
			NearPlayerModule.getInstance();
			OfficialModule.getInstance();
			PetModule.getInstance();
			PresentModule.getInstance();
			RankModule.getInstance();
			RewardModule.getInstance();
			RiderModule.getInstance();
			RobKingWarModule.getInstance();
			RobKingSceneCase.getInstance();
			RoleStateModule.getInstance();
			ShopModule.getInstance();
			SkillModule.getInstance();
			SkillTreeModule.getInstance();
			SmallMapModule.getInstance();
			SkillModule.getInstance();
			StatModule.getInstance();
			SystemModule.getInstance();
			PersonalYbcModule.getInstance();
			TeamModule.getInstance();
			PersonalYbcModule.getInstance();
			TrainModule.getInstance();
			WarehouseModule.getInstance();
			VipModule.getInstance();
			TradingModule.getInstance();
			MissionModule.getInstance();
			MissionFBModule.getInstance();
			NPCModule.getInstance();
			TrapModule.getInstance();
			SceneWarFbModule.getInstance();
			SpyModule.getInstance();
			HelpManager.getInstance();
			mountModule.getInstance();
			PlayerGuideModule.getInstance();
			NpcDealModule.getInstance();
			DriverModule.getInstance();
            GiftModule.getInstance();
			NeedfieModule.getInstance();
			FamilyCollectModule.getInstance();
			HeroFBModule.getInstance();
			FineryModule.getInstance();
			GoalModule.getInstance();
			MessageIconManager.getInstance();
			PrestigeModule.getInstance();
			MarketModule.getInstance();
			TouristModule.getInstance();
		}
	}
}